[workspace]
resolver = "3"
members = ["crates/psx-core", "crates/psx-cli", "crates/psx-desktop"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/Deivison-Costaa/psx-rs"

[profile.dev]
opt-level = 1
debug-assertions = true
overflow-checks = true

[profile.test]
opt-level = 1
debug-assertions = true
overflow-checks = true
