[package]
name = "psx-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
bincode = { version = "2", default-features = false, features = ["serde", "alloc"] }
